### ISSUE TITLE
Signal K from git now needs a build step

### ISSUE THREAD

**Issue by bergie** [tkurki/marinepi-provisioning#77]
We need to add a `npm run build` in the git checkout for the `signalk` role. Otherwise it'll fail to start with:

```
$ /usr/bin/node /opt/signalk-server/bin/signalk-server
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '../lib'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
```

**Comment by tkurki** [comment]
Is installing from git really necessary? My plan for the coming season is to run in Docker (like I did last season) or the standard way is to install from npm.

**Comment by bergie** [comment]
Well, the `node-app` setup for the `signalk` role uses git. I definitely see the appeal of going Docker (though preferably with containers run individually by systemd instead of docker-compose), but right now this seems to be the default installation method, and it broke when Signal K went TypeScript.

**Comment by tkurki** [comment]
Just in case you’ve missed it: https://github.com/tkurki/marinepi-provisioning/tree/master/roles/signalk-docker

**Comment by bergie** [comment]
Yup, I've seen that one. Comes with a bit more stuff than what I need so I've been sticking to the regular SK role
